services:
  board:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - ${BOARD_GRPC_EXTERNAL_PORT}:${BOARD_GRPC_PORT}
    volumes:
      - '.:/app'
    command: ["go", "run", "board/cmd/main.go"]
    depends_on:
      postgres-board:
        condition: service_healthy
  postgres-board:
    image: postgres:17.0-alpine3.20
    volumes:
      - postgres_board_data:/var/lib/postgresql/data
    ports:
      - "${EXTERNAL_POSTGRES_BOARD_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_BOARD_PASSWORD}
      POSTGRES_USER: ${POSTGRES_BOARD_USER}
      POSTGRES_DB: ${POSTGRES_BOARD_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_BOARD_USER} -d ${POSTGRES_BOARD_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_board_data:
networks:
  default:
    name: docker
    external: true